#!/usr/bin/env bash
# setup-ddns.sh — Install and configure ddclient for Namecheap DDNS on Ubuntu Server.
#
# Keeps the DNS A record for andykeys.me pointing at the server's current public IP.
# Run once on the server after a fresh setup or migration. Safe to re-run.
#
# Prerequisites:
#   - Namecheap account with Dynamic DNS enabled for the domain
#   - DDNS password from Namecheap → Advanced DNS → Dynamic DNS panel
#
# Usage:
#   bash scripts/infra/setup-ddns.sh

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────

DOMAIN="andykeys.me"
DDCLIENT_CONF="/etc/ddclient.conf"
DDCLIENT_DEFAULTS="/etc/default/ddclient"

# ── Helpers ───────────────────────────────────────────────────────────────────

info()  { echo -e "\033[0;36m[INFO]\033[0m  $*"; }
ok()    { echo -e "\033[0;32m[OK]\033[0m    $*"; }
warn()  { echo -e "\033[0;33m[WARN]\033[0m  $*"; }
die()   { echo -e "\033[0;31m[ERROR]\033[0m $*" >&2; exit 1; }

# ── Preflight ─────────────────────────────────────────────────────────────────

info "Setting up ddclient for $DOMAIN (Namecheap DDNS)"
echo ""

if [ "$EUID" -ne 0 ]; then
  die "Run as root: sudo bash scripts/infra/setup-ddns.sh"
fi

# ── Install ───────────────────────────────────────────────────────────────────

info "Installing ddclient..."
apt-get update -qq
# Non-interactive: on a fresh install the ddclient postinst script otherwise
# pops up a debconf/whiptail wizard asking for IP-discovery method, hosts,
# protocol, etc. — all of which get overwritten by the config we write below,
# so there's no reason to make this an interactive install.
DEBIAN_FRONTEND=noninteractive apt-get install -y ddclient > /dev/null
ok "ddclient installed"

# ── Prompt for credentials ────────────────────────────────────────────────────

echo ""
info "You need the DDNS password from Namecheap."
info "Find it at: Namecheap → Domain List → $DOMAIN → Advanced DNS → Dynamic DNS"
echo ""
printf "Enter Namecheap DDNS password for %s: " "$DOMAIN"
read -rs DDNS_PASSWORD
echo ""

if [ -z "$DDNS_PASSWORD" ]; then
  die "DDNS password cannot be empty."
fi

# ── Write config ──────────────────────────────────────────────────────────────

info "Writing $DDCLIENT_CONF ..."

cat > "$DDCLIENT_CONF" <<EOF
# ddclient configuration for $DOMAIN (Namecheap DDNS)
# Generated by scripts/infra/setup-ddns.sh
# See: https://www.namecheap.com/support/knowledgebase/article.aspx/583

daemon=300                              # check every 5 minutes
syslog=yes                              # log to syslog
pid=/run/ddclient/ddclient.pid
ssl=yes                                 # use HTTPS to update

use=web
web=dynamicdns.park-your-domain.com/getip

protocol=namecheap
server=dynamicdns.park-your-domain.com
login=$DOMAIN
password='$DDNS_PASSWORD'
@                                       # updates the root A record (@)
EOF

chmod 600 "$DDCLIENT_CONF"
ok "Config written to $DDCLIENT_CONF (mode 600)"

# ── Enable daemon mode ────────────────────────────────────────────────────────

if [ -f "$DDCLIENT_DEFAULTS" ]; then
  sed -i 's/^run_daemon=.*/run_daemon="true"/' "$DDCLIENT_DEFAULTS" 2>/dev/null || true
  sed -i 's/^daemon_interval=.*/daemon_interval="300"/' "$DDCLIENT_DEFAULTS" 2>/dev/null || true
fi

# ── Enable and start service ──────────────────────────────────────────────────

info "Enabling ddclient systemd service..."
systemctl enable ddclient
systemctl restart ddclient
sleep 2

if systemctl is-active --quiet ddclient; then
  ok "ddclient service is running"
else
  warn "ddclient service did not start cleanly — check: sudo journalctl -u ddclient -n 20"
fi

# ── Immediate update test ─────────────────────────────────────────────────────

echo ""
info "Running immediate update (verbose)..."
ddclient -daemon=0 -debug -verbose -noquiet 2>&1 | tail -20

# ── Verify ────────────────────────────────────────────────────────────────────

echo ""
info "Verifying DNS A record for $DOMAIN..."
CURRENT_PUBLIC_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "unknown")
DNS_IP=$(dig +short "$DOMAIN" @8.8.8.8 2>/dev/null | tail -1 || echo "unknown")

info "  Server public IP : $CURRENT_PUBLIC_IP"
info "  DNS A record     : $DNS_IP"

if [ "$CURRENT_PUBLIC_IP" = "$DNS_IP" ] && [ "$CURRENT_PUBLIC_IP" != "unknown" ]; then
  ok "DNS A record matches server public IP ✓"
else
  warn "DNS A record ($DNS_IP) does not yet match server IP ($CURRENT_PUBLIC_IP)"
  warn "This may be normal if the update was just sent — allow 1-3 minutes for propagation."
  warn "Re-check with: dig +short $DOMAIN @8.8.8.8"
fi

echo ""
ok "ddclient setup complete."
info "Service status : systemctl status ddclient"
info "Live logs      : sudo journalctl -u ddclient -f"
info "Manual trigger : sudo ddclient -daemon=0 -verbose -noquiet"
